### ISSUE TITLE
StatefulSet deployment failure

### ISSUE THREAD

**Issue by joeledwards** [npm-wharf/hikaru#2]
Cluster deployment fails due to absence of metadata in the `statefulSet` value passed in to the `createStatefulSet` function in `src/k8s/statefulSet.js`. The object received doesn't appear to be what we should expect.

Looking into the export of this function as `create`, it appears that the `statefulSet` parameter is being shadowed in the bind operation by `deletes`. This is preventing the actual statefulSet context from being passed to the create function unless the value of `deletes` happened to be `undefined` at the time of binding.

`create: createStatefulSet.bind(null, client, deletes),` fails for some cases
`create: createStatefulSet.bind(null, client),` works for all cases

The error:
```
2017-11-27T16:13:57.502Z - info     creating statefulSet 'postgres'
2017-11-27T16:13:57.502Z - info     creating statefulSet 'redis'
2017-11-27T16:14:28.694Z - error Failed to setup cluster resources with error:
	Cannot read property 'namespace' of undefined
	TypeError: Cannot read property 'namespace' of undefined
    at createStatefulSet (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/src/k8s/statefulSet.js:74:42)
    at getContainer (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/src/cluster.js:272:16)
    at create (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/src/cluster.js:37:12)
    at createContainer (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/src/cluster.js:47:12)
    at onRoleBindingCreated (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/src/cluster.js:512:10)
    at tryCatcher (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/jed/.npm-global/lib/node_modules/@npm-wharf/hikaru/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by joeledwards** [comment]
After reviewing other deployment 'kinds', it appears that the binding is correct, and it is actually the deletes parameter which is missing from the `createStatefulSet` function. The parameter is never used, but this is also the case in other create functions (e.g., `createCronJob`) as well.

**Comment by joeledwards** [comment]
Found an example of `deletes` being used in `src/k8s/deployment.js`. All other locations include the parameter, but do not reference it within the `create*` function.

**Comment by joeledwards** [comment]
Addressed in PR https://github.com/npm-wharf/hikaru/pull/3
